---
- name: setup  vprofile
  hosts: localhost
  gather_facts: false
  tasks: 
   - name: import vpc setup variable
     include_vars: vars/vpc-output_vars

   - name: import vprofile setup variable
     include_vars: vars/vprostacksetup
  
   - name: create vprofile ec2 key
     ec2_key:
       name: vprokey
       region: "{{region}}"
  
     register: vprokey_out 
  
   - name: save private key into bastion-host
     copy:
       content: "{{vprokey_out.key.private_key}}"
       dest: ./loginkey-key.pem
       mode: 0600
     when: vprokey_out.changed 

    

